---
title: "Generation of figures for the paper"
description: 
author:
  - name: Lars Relund Nielsen
    url: http://pure.au.dk/portal/en/larsrn@econ.au.dk
    affiliation: CORAL, BSS, Aarhus University
    affiliation_url: https://econ.au.dk/coral
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    toc: true
    toc_depth: 1
---

```{r, include = FALSE}
library(knitr)
library(rgl)
if (interactive()) setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
# setupKnitr()
# knitr::opts_chunk$set(
#   collapse = TRUE,
#   comment = "#>",
#   fig.path = "ublb-",
#   warning=FALSE, message=FALSE, include = TRUE, 
#   out.width = "99%", fig.width = 8, fig.align = "center", fig.asp = 0.62
# )
if (isTRUE(getOption('knitr.in.progress'))) options(rgl.useNULL=TRUE)
rgl::setupKnitr()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning=FALSE, message=FALSE, include = TRUE, 
  cache = TRUE, autodep = TRUE,
  echo=FALSE,
  out.width = "99%", fig.width = 8, fig.align = "center", fig.asp = 0.7
  # layout="l-page"   #"l-screen-inset"
)
knit_hooks$set(webgl = hook_webgl, rgl = hook_rgl)
options(knitr.kable.NA = '')
```

```{r setup, include=FALSE}
library(rgl)
library(gMOIP)
library(ggsci)
library(tidyverse)
library(tikzDevice)
library(magrittr)
library(RColorBrewer)
library(wesanderson)
library(kableExtra)
library(ggthemes)
library(rmarkdown)
rgl::par3d("family" = "serif")
pathOverLeaf <- "C:/Users/au15463/Dropbox/Apps/Overleaf/MT_paper_objective_branching"
```

```{r color scales, include=FALSE}
# https://cran.r-project.org/web/packages/ggsci/vignettes/ggsci.html
mypal <- pal_npg("nrc", alpha = 0.7)(9)
mypal <- pal_simpsons()(9)
# mypal
library("scales")
show_col(mypal)
```

```{r load instance results, include=FALSE}
toLink <- function(inst) {
  if (length(inst) == 0) return("")
  links <- str_c('../../docs/instances/', inst, '.html')
  url <- str_c('instances/', inst, '.html')
  if_else(file.exists(links), str_c('<a href="', url, '">', inst, '</a>'), inst)
}

limSec <- c(0, 30*60)  # computation time limits (exclude instances with max cpu < limSec[1] or  min cpu > limSec[2])
abbrv <- function(str) {
  str_replace_all(str, 
    c("breadth" = "B", "depth" = "D", "mof" = "F", "mfavg" = "A", "exact" = "F", 
      "cone" = "C", "none" = "N", "None" = "N", "spheredown" = "down", "sphereup" = "up"))
}
datAll <- read_csv("../statistics.csv") %>%   #"../convert/data/stat.csv"
  filter(coef == "spheredown", rangeC == "[1,1000]" | rangeC == "[1,1000]|[1,100]", varsel == "mof") %>% #| coef == "sphereup"
  mutate(YNsRatio = YNs/YN, 
         YNusRatio = 1-YNs/YN, 
         YNsneRatio = (YNs-YNse)/YN,
         algConfig = tolower(str_c(nodesel, varsel, OB, sep="|")),
         nodeselVarsel = tolower(str_c(nodesel, sep="|")),   #nodeselVarsel = tolower(str_c(nodesel, varsel, sep="|")),
         resultName = str_c(instance, algConfig, sep="_")) %>% 
  mutate(algConfig = tolower(str_c(nodesel, OB, sep="|")))
  # group_by(instance) %>% 
  # mutate(minCpu = min(tpstotal), maxCpu = max(tpstotal)) %>% 
  # mutate(unsolvedAllConfigs = if_else(maxCpu < limSec[1] | minCpu >= limSec[2], T, F))
algConfigsN <- length(unique(datAll$algConfig))

# tmp <- datAll %>% 
#   group_by(instance) %>% 
#   summarise(minCpu = min(tpstotal), maxCpu = max(tpstotal)) %>% 
#   filter(maxCpu < limSec[1] | minCpu > limSec[2]) %>% 
#   pull(instance)

tmp <- datAll %>% 
  group_by(pb, n, coef) %>% 
  mutate(allUnsolved = 1 - max(solved)) %>% 
  ungroup() %>% 
  filter(allUnsolved == 1) %>% 
  pull(instance)

datAll <- datAll %>% 
  filter(!(instance %in% tmp)) %>%
  mutate(solved = if_else(tpstotal >= limSec[2] | solved == 0, 0, 1)) %>% 
  # group_by(instance) %>% 
  # filter(n() == algConfigsN) %>% 
  # ungroup() %>% 
  mutate(tpstotal = if_else(tpstotal >= limSec[2], limSec[2], tpstotal),
         algConfig = abbrv(algConfig),
         coef = abbrv(coef),
         nodeselVarsel = abbrv(nodeselVarsel),
         OB = abbrv(OB))
# View(datAll %>% group_by(instance) %>% summarise(ctr = n()))
algConfigs <- unique(datAll$algConfig)
nodeselVarselConfigs <- unique(datAll$nodeselVarsel)
datNotSolved <- datAll %>% filter(solved == 0) 
datSolved <- datAll %>% filter(solved == 1)
datInput <- datAll %>% 
  group_by(instance) %>%
  mutate(unsolved = 1-max(solved)) %>%
  ungroup() %>%
  distinct(instance, .keep_all = TRUE) %>% 
  select(instance, pb, n, p, coef, contains("range"), ratioNDcoef, unsolved)
# instances with all configs run

datWin <- 
  datAll %>% 
  group_by(instance) %>% 
  nest() %>% 
  mutate(winner = map(data, function(df) {df %>% arrange(tpstotal) %>% slice(1)})) %>% 
  mutate(win = map(winner, function(df) {if_else(df$solved == 1, df$algConfig, "Unsolved")})) %>% 
  select(-winner) %>% 
  unnest(c(data, win)) 

datNotStable <- read_csv("../convert/data/stat.csv", col_types = cols()) %>%
  filter(coef == "spheredown", rangemax == 1000, solved == 1) %>% #| coef == "sphereup"
  group_by(instance) %>%
  distinct(YN) %>%
  summarise(ctr = n()) %>%
  dplyr::filter(ctr > 1)
if (nrow(datNotStable) > 0) stop("Instabilities found!")

datObNC <- datAll %>% filter(OB == "N" | OB == "C")

tmp <- tibble(algConfig = datAll %>% pull(algConfig) %>% unique()) %>% separate(algConfig, c("nodeselVarsel", "OB"), remove = F, sep = "\\|")
datAllJoined <- datAll %>% 
  group_by(instance) %>% 
  nest() %>% 
  mutate(missing = map(data, function(df) full_join(df, tmp, by = c("algConfig", "nodeselVarsel", "OB")) %>% mutate(pb = df$pb[1]))) %>% 
  select(-data) %>% 
  unnest(missing) %>% 
  replace_na(list(tpstotal = 1800)) 

datOSS <- read_csv("../statistics_oss.csv") 
```

```{r Define theme and color scales, include=FALSE}
theme_publish <- function() {
  library(grid)
  library(ggthemes)
  return(theme_foundation(base_size = 10) +
    theme(
      # plot.title = element_text(face = "bold", size = rel(1.2), hjust = 0.5),
      text = element_text(face = "plain"),
      # panel.background = element_rect(colour = NA),
      panel.spacing = unit(0.5, "cm"),
      plot.background = element_blank(),
      # panel.border = element_rect(colour = NA),
      axis.title = element_text(face = "plain",size = rel(1)),
      # axis.title.y = element_text(angle=90,vjust =2),
      # axis.title.x = element_text(vjust = -0.2),
      axis.text = element_text(),
      axis.line = element_line(colour="black"),
      axis.ticks = element_line(),
      panel.grid.major = element_line(colour="#f0f0f0"),
      panel.grid.minor = element_blank(),
      legend.key = element_rect(colour = NA),
      legend.position = "bottom",
      legend.direction = "horizontal",
      # legend.key.size = unit(0.2, "cm"),
      legend.key.height = unit(0.2, "cm"), 
      legend.key.width = unit(0.75, "cm"),
      # legend.margin = unit(0, "cm"),
      legend.title = element_blank(), #element_text(face="italic"),
      # plot.margin=unit(c(10,5,5,5),"mm"),
      # strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
      # strip.text = element_text(face="bold"),
    )
  )
}


# scale_fill_Publication <- function(...){
#       library(scales)
#       discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)
# 
# }
# 
# scale_colour_Publication <- function(...){
#       library(scales)
#       discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)
# 
# }



# display.brewer.pal(n = 11, name = "RdYlBu")
pal <- brewer.pal(n = 11, name = "RdYlBu")
# algConfigs <- algConfigs[c(2,5, 3,6, 1,4, 8,11, 9,12, 7,10)]
palAlgConfigs <- wes_palette("Zissou1", algConfigsN, type = "continuous")
palAlgConfigs <- c(brewer.pal(n =  algConfigsN/2, name = "Reds"), brewer.pal(n =  algConfigsN/2, name = "Blues"))
# display.brewer.pal(n = 9, name = "Blues")
# brewer.pal(n = 6, name = "Greens")

scale_color_algConfig <- scale_color_manual(
  values = setNames(palAlgConfigs, algConfigs),
  drop = F)
scale_fill_algConfig <- scale_fill_manual(
  values = setNames(palAlgConfigs, algConfigs),
  drop = F)

scale_color_nodesel_varsel <- scale_color_manual(
  values = setNames(pal[c(1,3,9,11)], nodeselVarselConfigs),
  drop = F)

scale_color_ob <- scale_color_manual(
  values = setNames(pal[c(1,3,9,11)], c("C", "F", "N", "OSS")),
  drop = F)

scale_fill_ob <- scale_fill_manual(
  values = setNames(pal[c(1,3,9,11)], c("C", "F", "N", "Unsolved")),
  drop = F)

scale_linetype_ob <- scale_linetype_manual(
  values = c("C" = 1, "F" = 2, "N" = 3),
  drop = F)

# scale_color_nodesel <- scale_color_manual(
#   values = c("breadth" = "red", "depth" = "green"),
#   drop = F)

# scale_alpha_varsel <- scale_alpha_manual(
#   values = c("mof" = 1, "mfavg" = 0.75),
#   drop = F)

# scale_linetype_valsel <- scale_linetype_manual(
#   values = c("mof" = 1, "mfavg" = 2),
#   drop = F)
  

scale_linetype_nodesel_varsel <- scale_linetype_manual(
  values = c("B" = 1, "D" = 2, "OSS" = 3, "Unsolved" = 1),
  drop = F)
```



## Figure 1

Saved as TikZ in file `fig_lb_ub_2d.tex`. 

```{r}
bBox <- list(m = c(0,0), M = c(12,14))
lb <- 
  tibble(z1 = c(1, 2, 4, 8), 
         z2 = c(8, 4, 2, 1))
# p <- plotHull2D(lb, drawPoints = F, addRays = T, m = bBox$m, M = bBox$M) 
ub <- 
  tibble(z1 = c(2, 4, 6, 9), 
         z2 = c(7, 4, 3, 2))
# p <- p + 
#   geom_point(aes(x = z1, y = z2), data=ub) +
#   plotCones2D(ub, drawPlot = F, m = bBox$m, M = bBox$M, drawLines = F,
#               argsGeom_polygon = list(fill = "white", alpha = 1))
lUb <- 
  tibble(z1 = c(2,  4, 6, 9, 12), 
         z2 = c(14, 7, 4, 3, 2 ))
# p <- p + 
#   geom_point(aes(x = z1, y = z2), shape = 15, data=lUb)
# p + 
#   xlab("$z_1$") + ylab("$z_2$") +
#   xlim(bBox$m[1], bBox$M[1]) + ylim(bBox$m[2], bBox$M[2]) + 
#   gMOIPTheme() + 
#   theme(axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.title.y=element_blank(),
#         axis.text.y=element_blank(),
#         axis.ticks.y=element_blank())

conesLB <- plotHull2D(lb, drawPoints = F, addRays = T, m = bBox$m, M = bBox$M, drawPlot = F, drawLines = F,
                   argsGeom_polygon = list(fill = mypal[2], alpha = 0.5)) 
ptsUB <- geom_point(aes(x = z1, y = z2, shape = "rou"), data = ub, show.legend = T) 
conesLUB <- plotCones2D(lUb, drawPlot = F, m = bBox$m, M = bBox$M, drawLines = F, direction = -1,
                     drawPoint = F, argsGeom_polygon = list(fill = mypal[1], alpha = 0.5))
lbLines <- geom_line(aes(x = z1, y = z2), data = lb)
ptsLUB <- geom_point(aes(x = z1, y = z2, shape = "sq"), data = lUb, show.legend = T)
layO <- ggplot() +
  xlim(bBox$m[1], bBox$M[1]) + ylim(bBox$m[2], bBox$M[2]) +
  gMOIPTheme() +
  theme(
    legend.position = c(0.85,0.85),
    legend.background = element_blank(),
  #   # axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
  #   # axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()) +
  xlab("$z_1$") + ylab("$z_2$")

p <- layO + conesLUB + conesLB + ptsUB + ptsLUB + lbLines +
  # geom_text(aes(x = z1, y = z2, label = 1:nrow(lb)), data = lb) +
  # geom_text(aes(1.5,2, label = "$A$")) + 
  geom_text(aes(2.75,5.5, label = "$\\mathcal{A}(\\mathcal{L},\\mathcal{U})$")) + 
  # geom_text(aes(7,10, label = "$A$")) +
  geom_text(aes(lb$z1[1], lb$z2[1]-2, label = "$\\mathcal{L}$"), nudge_x = 0.15) + 
  scale_shape_manual(
    values = c(rou = 19, sq = 15), 
    labels = c("$\\mathcal{U}$", "$\\mathcal{N}(\\mathcal{U})$"), name = NULL)
p  

# layO + cones + hull +# ptsUB + ptsLUB 
#   geom_line(aes(x = 1, y = 1, linetype = "lb")) +
#   geom_col(aes(x = 1, y = 1, fill = c("noSol", "dom"))) +
#   scale_linetype_manual(values = c(lb = 1)) + 
#   scale_fill_manual(values = c(noSol = mypal[1], dom = mypal[2]))
  
fName <- "fig_lb_ub_2d.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F, width = 7, height = 5)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


## Figure 2

Saved as TikZ in file `fig_ob_2d.tex`. 

```{r}
bBox <- list(m = c(0,0), M = c(14,11))
lb <- 
  tibble(z1 = c(2, 4, 13), 
         z2 = c(9, 5, 0.5))
lUb <- 
  tibble(z1 = c(1,  3, 5, 7, 8, 9, 14), 
         z2 = c(11, 9, 6, 5, 3, 2, 1))
ub <- 
  tibble(z1 = c(1, 3, 5, 7, 8, 9), 
         z2 = c(9, 6, 5, 3, 2, 1))
ob <-   
  tibble(z1 = c(3, 7, 14), 
         z2 = c(9, 6, 1))
ptsOB <- geom_point(aes(x = z1, y = z2), data = ob, shape = 21, size = 5, color = mypal[5])
ptsOBText <- geom_text(aes(x = z1, y = z2), data = ob, label = c("$y^1$", "$y^2$", "$y^3$"), nudge_y = 0.5)
conesOB <- plotCones2D(ob, drawPlot = F, m = bBox$m, M = bBox$M, drawLines = T, direction = -1,
                     drawPoint = F, argsGeom_polygon = list(fill = NA, alpha = 0.5), argsGeom_path = list(linetype = 3, size = 0.9))
conesLB <- plotHull2D(lb, drawPoints = F, addRays = T, m = bBox$m, M = bBox$M, drawPlot = F, drawLines = F,
                   argsGeom_polygon = list(fill = mypal[2], alpha = 0.5)) 
ptsUB <- geom_point(aes(x = z1, y = z2, shape = "rou"), data = ub, show.legend = T) 
conesLUB <- plotCones2D(lUb, drawPlot = F, m = bBox$m, M = bBox$M, drawLines = F, direction = -1,
                     drawPoint = F, argsGeom_polygon = list(fill = mypal[1], alpha = 0.5))
lb1 <- tibble(z1 = c(12,13), z2 = 7 - 0.5*c(12,13))
lbLines1 <- geom_line(aes(x = z1, y = z2), data = lb1, linetype = 1)
lb2 <- tibble(z1 = c(3.5, 4), z2 = 13 - 2*c(3.5, 4))
lbLines2 <- geom_line(aes(x = z1, y = z2), data = lb2, linetype = 1)
lb3 <- tibble(z1 = c(4,7), z2 = 7 - 0.5*c(4,7))
lbLines3 <- geom_line(aes(x = z1, y = z2), data = lb3, linetype = 1)
lb4 <- tibble(z1 = c(2, 3), z2 = 13 - 2*c(2, 3))
lbLines4 <- geom_line(aes(x = z1, y = z2), data = lb4, linetype = 1)
lb5 <- tibble(z1 = c(7,12), z2 = 7 - 0.5*c(7,12))
lbLines5 <- geom_line(aes(x = z1, y = z2), data = lb5, linetype = 2)
lb6 <- tibble(z1 = c(3, 3.5), z2 = 13 - 2*c(3, 3.5))
lbLines6 <- geom_line(aes(x = z1, y = z2), data = lb6, linetype = 2)
ptsLUB <- geom_point(aes(x = z1, y = z2, shape = "sq"), data = lUb, show.legend = T)
layO <- ggplot() +
  xlim(bBox$m[1], bBox$M[1]) + ylim(bBox$m[2], bBox$M[2]) +
  gMOIPTheme() +
  theme(
    legend.position = c(0.85,0.85),
    legend.background = element_blank(),
  #   # axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
  #   # axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()) +
  xlab("$z_1$") + ylab("$z_2$")
p <- layO + conesLUB + conesLB + conesOB + ptsUB + ptsOB + ptsLUB + ptsOBText +
  lbLines1 + lbLines2 + lbLines3 + lbLines4 + lbLines5 + lbLines6 +
  # geom_text(aes(2.75,5.5, label = "$\\mathcal{A}(\\mathcal{L},\\mathcal{U})$")) + 
  # geom_text(aes(lb$z1[1], lb$z2[1]-2, label = "$\\mathcal{L}$"), nudge_x = 0.15) + 
  scale_shape_manual(
    values = c(rou = 19, sq = 15), 
    labels = c("$\\mathcal{U}$", "$\\mathcal{N}(\\mathcal{U})$"), name = NULL)
p  
fName <- "fig_ob_2d.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F, width = 7, height = 5)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


## Figure 3

### Figure 3a

```{r}
bBox <- list(m = c(0,0), M = c(7,7))
lb <- 
  tibble(z1 = c(1, 6), 
         z2 = c(6, 1))
lUb <- 
  tibble(z1 = c(3, 7), 
         z2 = c(7, 3))
ub <- 
  tibble(z1 = c(3), 
         z2 = c(3))
ob <-   
  tibble(z1 = c(3, 3, 7), 
         z2 = c(7, 3, 3))
lb1 <- tibble(z1 = c(1,3), z2 = 7 - c(1,3))
lb2 <- tibble(z1 = c(3,4), z2 = 7 - c(3,4))
lb3 <- tibble(z1 = c(4,6), z2 = 7 - c(4,6))
conesOB <- plotCones2D(ob, drawPlot = F, m = bBox$m, M = bBox$M, drawLines = T, direction = -1,
                     drawPoint = F, argsGeom_polygon = list(fill = NA, alpha = 0.5), argsGeom_path = list(linetype = 3, size = 0.5))
conesLB <- plotHull2D(lb, drawPoints = F, addRays = T, m = bBox$m, M = bBox$M, drawPlot = F, drawLines = F,
                   argsGeom_polygon = list(fill = mypal[2], alpha = 0.5)) 
ptsUB <- geom_point(aes(x = z1, y = z2, shape = "rou"), data = ub, show.legend = T) 
conesLUB <- plotCones2D(lUb, drawPlot = F, m = bBox$m, M = bBox$M, drawLines = F, direction = -1,
                     drawPoint = F, argsGeom_polygon = list(fill = mypal[1], alpha = 0.5))
lbLines1 <- geom_line(aes(x = z1, y = z2), data = lb1, linetype = 1)
lbLines2 <- geom_line(aes(x = z1, y = z2), data = lb2, linetype = 2)
lbLines3 <- geom_line(aes(x = z1, y = z2), data = lb3, linetype = 1)
ptsLUB <- geom_point(aes(x = z1, y = z2, shape = "sq"), color = mypal[8], data = lUb)
layO <- ggplot() +
  xlim(bBox$m[1], bBox$M[1]) + ylim(bBox$m[2], bBox$M[2]) +
  gMOIPTheme() +
  theme(
    # legend.position = "none",
    legend.background = element_blank(),
  #   # axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
  #   # axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()) +
  xlab("$z_1$") + ylab("$z_2$")
p <- layO + conesLUB + conesLB + conesOB + ptsUB + ptsLUB + 
  lbLines1 + lbLines2 + lbLines3 +
  # geom_text(aes(2.75,5.5, label = "$\\mathcal{A}(\\mathcal{L},\\mathcal{U})$")) + 
  # geom_text(aes(lb$z1[1], lb$z2[1]-2, label = "$\\mathcal{L}$"), nudge_x = 0.15) + 
  scale_shape_manual(
    values = c(rou = 19, sq = 19), 
    labels = c("$\\mathcal{U}$", "$\\mathcal{N}(\\mathcal{U})$"), name = NULL)
p  
fName <- "fig_ob_pt_2d.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```



### Figure 3b

```{r}
ubSet <- matrix( c(1,1,1), ncol = 3, byrow = TRUE)
row.names(ubSet) <- paste0("z", 1)
lim <- c(0,7)  # bounding box for problem
m <- rep(lim[1],3)
M <-rep(lim[2],3)
augment <- function(idx, a, b, prefix = "") {
  res <- NULL
  for (i in idx) {
    c <- b
    c[i] <- a[i]
    res <- rbind(res,c)
  }
  row.names(res) <- paste0(prefix,idx)
  return(res)
}
zHat <- augment(1:3, M, m)
# iteration 0
U <- matrix(M, ncol = 3, byrow = T)
row.names(U) <- "u0"
N <- NULL
NHat <- rbind(N,zHat)
z <- ubSet[1,1:3]
u0 <- M
U <- augment(1:3, z, u0, "u")
N<- rbind(N, ubSet[1,1:3, drop=F])

view <- matrix( c(-0.640044808387756, -0.205455526709557, 0.740358412265778, 0, 0.767741799354553, -0.208960145711899, 0.605729579925537, 0, 0.0302549730986357, 0.956098079681396, 0.29148057103157, 0, 0, 0, 0, 1), nc = 4)

# rgl::mfrow3d(nr = 1, nc = 2, sharedMouse = F)

lim <- c(lim[1]-0.05,lim[2]+0.05)
## First plot
# ini3D(argsPlot3d = list(xlim = lim, ylim = lim, zlim = lim))
# # plotRectangle3D(m,M)
# plotPoints3D(N, addText = "coord", argsPlot3d = list(type="p", col = "black", size = 8))
# plotPoints3D(U, addText = "coord", argsPlot3d = list(type="p", col = mypal[3], size = 8), argsText3d = list(col = "blue", adj = c(1,1)))
# plotPlane3D(c(1,1,1), point = c(2,2,2), argsLines = list(col = mypal[2], lines = 50), useLines = T, useShade = F)
# plotPlane3D(c(1,1,1), point = c(2,2,2), argsPlanes3d = list(alpha = 0.7, col = mypal[8]))
# plotCones3D(U[1:3,], drawPoint = F, argsPolygon3d = list(alpha =0.3, color = mypal[1]), rectangle = F, direction = -1, drawLines = F)
# finalize3D(argsAxes3d = list(edges = "bbox", box = F))
# loadView(v = view, clear = FALSE, zoom = 0.7)
# rglwidget()

## all relevant points for drawing search areas
vtx <- matrix(c(
  1,1,4,
  1,4,1,
  4,1,1,
  0,0,7,
  0,7,0,
  7,0,0,
  0,0,6,
  0,6,0,
  6,0,0,
  0,1,5,
  0,5,1,
  1,0,5,
  1,5,0,
  5,0,1,
  5,1,0,
  1,1,7,
  1,7,1,
  7,1,1,
  7,1,0,
  7,0,1,
  1,7,0,
  1,0,7,
  0,7,1,
  0,1,7,
  7,7,0,
  7,0,7,
  0,7,7,
  7,1,7,
  7,7,1,
  1,7,7
), ncol = 3, byrow = T)
vtx <- vtx %>% set_colnames(c("x", "y", "z")) %>% as_tibble() %>% arrange(x,y,z)
# plotPoints3D(vtx, addText = "coord")
# print(vtx, n=100)


ini3D(argsPlot3d = list(xlim = lim, ylim = lim, zlim = lim))
# Points
plotPoints3D(N, argsPlot3d = list(type="p", col = "black", size = 10))
plotPoints3D(U, argsPlot3d = list(type="p", col = mypal[8], size = 10), argsText3d = list(col = "blue", adj = c(1,1)))
# plotCones3D(c(1,1,1), argsPolygon3d = list(alpha = 0.9, color = mypal[4]))
# Plane
plotPlane3D(c(1,1,1), point = c(2,2,2), argsPlanes3d = list(alpha = 0.75, col = mypal[2]))
plotPlane3D(c(1,1,1), point = c(2,2,2), argsLines = list(col = "black", lines = 100, alpha = 0.75), useLines = T, useShade = F)
# Overlapping areas
args <- list(color = mypal[5], alpha = 0.9)
plotHull3D(vtx[c(19:24,26:27),], drawPolygons = T, argsPolygon3d = args)
vtx <- vtx %>% arrange(y,x,z)
plotHull3D(vtx[c(19:24,26:27),], drawPolygons = T, argsPolygon3d = args)
vtx <- vtx %>% arrange(z,y,x)
plotHull3D(vtx[c(19:24,26:27),], drawPolygons = T, argsPolygon3d = args)
# Non-overlapping areas
args <- list(color = mypal[3], alpha = 0.4)
plotHull3D(vtx[c(10,11,12,13,19,20,24,25,27,28),] , drawPolygons = T, argsPolygon3d = args)
vtx <- vtx %>% arrange(y,x,z)
plotHull3D(vtx[c(10,11,12,13,19,20,24,25,27,28),] , drawPolygons = T, argsPolygon3d = args)
vtx <- vtx %>% arrange(y,z,x)
plotHull3D(vtx[c(10,11,12,13,19,20,24,25,27,28),] , drawPolygons = T, argsPolygon3d = args)
finalize3D(argsAxes3d = list(edges = c("x", "y", "z"), box = F, labels=FALSE, tick=FALSE))
# finalize3D(argsAxes3d = list(edges = "bbox"))
#axes3d(edges=c("x", "y", "z"), col='black', box=FALSE, labels=FALSE, tick=FALSE)
#rgl.bbox(xlab = "", ylab = "", zlab = "")
view <- matrix( c(-0.601261854171753, -0.375613540410995, 0.705264508724213, 0, 0.79587709903717, -0.36011865735054, 0.48671817779541, 0, 0.071161076426506, 0.853949129581451, 0.515467822551727, 0, 0, 0, 0, 1), nc = 4)
loadView(v = view, clear = F, zoom = 0.8)
rglwidget()
# saveView(print=TRUE)

fName <- "fig_ob_pt_3d.png"
if (isFALSE(getOption('knitr.in.progress'))) {
  snapshot3d(fName) 
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```





## Figure 4

### Figure 4a

```{r}
# pts <- genNDSet(3, 50, argsSphere = list(below = NULL, closeToPlane = T, center = c(2,2,2), radius = 5), dubND = F)
# save(pts, file = "pts_fig4.Rdata")
load("pts_fig4.Rdata")

## First plot
# open3d()
# rgl::mfrow3d(nr = 1, nc = 2, sharedMouse = F)
ini3D(argsPlot3d = list(xlim = c(min(pts$z1)-2,max(pts$z1)+10), 
                        ylim = c(min(pts$z2)-2,max(pts$z2)+10), 
                        zlim = c(min(pts$z3)-2,max(pts$z3)+10)))
lub <- Rfast::colMinsMaxs(as.matrix(pts[,1:3]))[2,]
M <- rgl::par3d()$bbox
lub <- rbind(lub, c(M[2],M[4],M[6])-0.01)
llb <- c(M[1],M[3],M[5])+ 0.01
# plotPoints3D(pts)
plotCones3D(pts[pts$nd,c("z1","z2","z3")], argsPolygon3d = list(alpha = 1, color = mypal[8]), drawPoint = T, rectangle = T, argsPlot3d = list(size = 10))
plotCones3D(lub[2,], direction = -1, argsPolygon3d = list(alpha = 0.4, color = mypal[1]), drawPoint = F)
# plotHull3D(unique(pts))
plotPlane3D(c(1,1,1), point = c(3,3,3), argsPlanes3d = list(alpha = 0.6, col = mypal[7]))
root <- currentSubscene3d()
newSubscene3d(
  "inherit",
  "inherit",
  "inherit",
  copyShapes = T,
  copyBBoxDeco = F,
  parent = root
)
plotCones3D(llb, argsPolygon3d = list(alpha = 0.75, color = mypal[3]), drawPoint = F)
# plotHull3D(unique(pts))
clipplanes3d(1, 1, 1, -9)
useSubscene3d(root)
# axes3d()
finalize3D(argsAxes3d = list(edges = "bbox"), argsTitle3d = list(xlab = "", ylab = "", zlab = ""))
# saveView(print = T)
view <- matrix( c(0.710081100463867, -0.417695313692093, -0.566847920417786, 0, -0.695306360721588, -0.288975149393082, -0.658059477806091, 0, 0.111063443124294, 0.861408114433289, -0.495621830224991, 0, 0, 0, 0, 1), nc = 4)
loadView(v = view, clear = FALSE, zoom = 0.7)
rglwidget()
fName <- "fig_ob_cicle_3d_1.png"
if (isFALSE(getOption('knitr.in.progress'))) {
  snapshot3d(fName) 
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```

### Figure 4b

```{r}
## Second plot
ini3D(clear = T, argsPlot3d = list(xlim = c(min(pts$z1)-2,max(pts$z1)+10), 
                        ylim = c(min(pts$z2)-2,max(pts$z2)+10), 
                        zlim = c(min(pts$z3)-2,max(pts$z3)+10)))
# plotPoints3D(pts)
plotPlane3D(c(1,1,1), point = c(3,3,3), argsPlanes3d = list(alpha = 0.6, col = mypal[7]))
plotCones3D(lub, direction = -1, argsPolygon3d = list(alpha = 1, color = mypal[1]), drawPoint = T)
plotmath3d(lub-1, text = expression(y^1, y^2), cex = 1.2, font = 3)
root <- currentSubscene3d()
# newSubscene3d(
#   "inherit",
#   "inherit",
#   "inherit",
#   copyShapes = T,
#   copyBBoxDeco = F,
#   parent = root
# )
# plotCones3D(llb, argsPolygon3d = list(alpha = 0.75, color = mypal[3]), drawPoint = F)
# plotHull3D(unique(pts))
# clipplanes3d(1, 1, 1, -9)
newSubscene3d(
  "inherit",
  "inherit",
  "inherit",
  copyShapes = T,
  copyBBoxDeco = F,
  parent = root
)
plotCones3D(pts[pts$nd,c("z1","z2","z3")], argsPolygon3d = list(alpha = 1, color = mypal[8]), drawPoint = T, drawLines = T, argsPlot3d = list(size = 10))
clipplanes3d(-1, -1, -1, 9)
useSubscene3d(root)
# axes3d()
finalize3D(argsAxes3d = list(edges = "bbox"), argsTitle3d = list(xlab = "", ylab = "", zlab = ""))
view <- matrix( c(0.860876560211182, -0.30657571554184, -0.406083613634109, 0, -0.448700070381165, -0.081096462905407, -0.889995634555817, 0, 0.239919260144234, 0.948385238647461, -0.207374647259712, 0, 0, 0, 0, 1), nc = 4)
loadView(v = view, clear = FALSE, zoom = 0.7)
rglwidget()
fName <- "fig_ob_cicle_3d_2.png"
if (isFALSE(getOption('knitr.in.progress'))) {
  snapshot3d(fName) 
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


# Figure 5

```{r}
tmp <- datAll %>%
  group_by(algConfig, pb) %>%
  arrange(tpstotal) %>%
  mutate(count = row_number(), total = n()) %>% 
  group_by(pb) %>% 
  mutate(total = max(total)) %>% 
  group_by(pb, algConfig, tpstotal) %>% 
  arrange(pb, algConfig, tpstotal, count) %>% 
  filter(tpstotal < 1800 | row_number() == 1) %>% 
  mutate(pct = count/total) %>% 
  select(pb, algConfig, tpstotal, count, pct, total, OB, nodeselVarsel)
```

```{r perfPlotPct, fig.asp=1, fig.cap="Performance profile: Number of instances in percent solved given cpu time. An instance is considered as unsolved if the cpu time exceed 1800 seconds (time limit)."}
p <- ggplot(tmp) +
  # geom_step(aes(x=tpstotal, y=count, color = nodeselVarsel, linetype = OB)) +
  geom_step(aes(y=pct, x=tpstotal, color = OB, linetype = nodeselVarsel), alpha = 0.75) +
  # geom_point(aes(y=..y.., x=tpstotal, color = OB, linetype = nodeselVarsel), stat="ecdf", size = 1) +
  facet_grid(rows = vars(pb)) +
  # ggtitle(str_c("Number of instances solved within a given cpu time")) +
  labs(color = "nS:", linetype = "oB:") +
  scale_color_ob + scale_linetype_nodesel_varsel +
  xlab("cpu (seconds)") + ylab("\\%") +
  theme_publish() +
  coord_cartesian(expand = FALSE, ylim = c(0, NA), xlim = c(-10, 1797))
p
fName <- "fig_pref_pct.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


# Figure 6

```{r winConfigs, fig.cap="Proportion of winning algorithm configurations."}
res <- datWin %>% 
  group_by(instance) %>%
  # filter(n() == algConfigsN, min(solved) == 1) %>% 
  group_by(pb, n) %>% 
  mutate(count = n()) %>% 
  group_by(pb, n, win) %>% summarize(pct = n()/mean(count)) %>% 
  arrange(pb, n, desc(pct)) %>% 
  separate(win, into = c("nodeselVarsel","OB"), sep = "\\|", remove = F) %>% 
  mutate(OB = replace_na(OB, "Unsolved"))
p <- ggplot(res, aes(x = factor(n), y = pct, fill = OB, linetype = nodeselVarsel)) + 
  geom_col(color = "black") + 
  geom_text(aes(label = round(pct, 2)), colour="white", size=2.5,
              position = position_stack(vjust = .5)) +
  scale_fill_ob + scale_linetype_nodesel_varsel +
  facet_grid(cols = vars(pb), margins = F, scales = "free") +
  ylab("\\% of instances") + xlab("n") +
  theme_publish()
p
fName <- "fig_win.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F, width = 7, height = 5)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


# Figure 7

```{r, eval=FALSE}
p <- datAll %>% 
  group_by(instance) %>%
  filter(n() == algConfigsN, min(solved) == 1) %>%
  ungroup() %>% 
  group_by(pb, OB, nodeselVarsel) %>% 
  summarise(node = mean(nbnodes)) %>% 
  group_by(pb) %>% 
  arrange(node) %>% 
  ggplot(aes(x = pb, y = node, fill = OB, linetype = nodeselVarsel)) + 
  geom_col(position = "dodge2", color = "black") +
  # geom_line(alpha = 0.75) +
  # geom_point(alpha = 0.75) +
  facet_grid(cols = vars(pb), scales = "free") + 
  # ggtitle(str_c("Average branching tree size.")) +
  labs(color = "oB:", linetype = "nS:") +
  scale_fill_ob + scale_linetype_nodesel_varsel +
  theme_publish() + theme() +
  xlab("problem class") + ylab("tree size")  
p
fName <- "fig_btree.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F, width = 7, height = 5)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


# Figure 8

```{r perfPlotND, fig.cap="Smoothed curves of relative number of non-dominated points compared to relative cpu."}
instancesNCSolved <- datAll %>%
  filter(OB == "C" | OB == "N") %>% 
  group_by(instance) %>%
  filter(min(solved) == 1) %>% 
  pull(instance)

csvFiles <- list.files("..", ".csv", full.names = T) %>% 
  str_subset("nd")
dat <- NULL
for (f in csvFiles) dat <- bind_rows(dat, read_csv(f))
dat <- dat %>% mutate(algConfig = abbrv(algConfig))
dat1 <- dat %>% 
  separate(algConfig, into = c("nodesel", "varsel", "OB"), sep = "_", remove = F) %>%
  mutate(pb = str_replace(instance, "^Forget20-(.*?)_.*$", "\\1")) %>% 
  filter(instance %in% instancesNCSolved, varsel == "F", OB == "N" | OB =="C") 

csvFiles <- list.files("..", ".csv", full.names = T) %>% 
  str_subset("points_oss")
dat <- NULL
for (f in csvFiles) dat <- bind_rows(dat, read_csv(f))
dat1 <- bind_rows(dat1, dat) %>% 
  mutate(nodesel = replace_na(nodesel, "OSS")) %>% 
  filter(instance %in% instancesNCSolved)

p <- ggplot(aes(x = pctCpu, y = pct, linetype = nodesel), data = dat1) + 
  geom_smooth(color = "black", se = F, size = 0.5) + 
  # facet_grid(rows = vars(pb)) +
  coord_cartesian(expand = FALSE, ylim = c(0, 1), xlim = c(0, 1)) +
  # ggtitle(str_c("Number of instances solved within a given cpu time")) +
  # labs(linetype = "") +
  scale_linetype_nodesel_varsel +
  theme_publish() + ylab("\\% of non-dominated points") + xlab("\\% of cpu time")
p
fName <- "fig_pref_nd.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F, width = 7, height = 5)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```


# Figure 9

```{r}
dat1 <- datOSS %>% 
  mutate(algConfig = "OSS", 
         pb = str_replace(instance, "Forget20-(.*?)_.*", "\\1"),
         tpstotal = cpu, alg = "OSS")
dat2 <- datAll %>% 
  filter (OB == "C" | OB == "N", instance %in% dat1$instance) %>% 
  mutate(alg = "BB")
dat <- bind_rows(dat2, dat1) %>% 
  group_by(instance) %>% 
  mutate(n = first(n)) %>% 
  group_by(algConfig, pb) %>%
  arrange(tpstotal) %>%
  mutate(count = row_number(), total = n()) %>% 
  group_by(pb) %>% 
  mutate(total = max(total)) %>% 
  group_by(pb, algConfig, tpstotal) %>% 
  arrange(pb, algConfig, tpstotal, count) %>% 
  filter(tpstotal < 1800 | row_number() == 1) %>% 
  mutate(pct = count/total) %>% 
  select(pb, algConfig, tpstotal, count, pct, total, n) %>% 
  separate(algConfig, into = c("nodeselVarsel", "OB"), sep = "\\|", remove = F) %>% 
  mutate(OB = replace_na(OB, "OSS"))

datWinner <- dat2 %>% 
  group_by(instance) %>% 
  nest() %>% 
  mutate(winner = map(data, function(df) {df %>% arrange(tpstotal) %>% slice(1)})) %>% 
  select(-data) %>% 
  unnest(c(winner))
```


```{r perfPlotPctOss, fig.asp=1.2, fig.cap="Performance profile: Number of instances in percent solved given cpu time. An instance is considered as unsolved if the cpu time exceed 1800 seconds (time limit)."}
p <- ggplot(dat) +
  geom_step(aes(y=pct, x=tpstotal, color = OB, linetype = nodeselVarsel), alpha = 0.75) + 
  facet_grid(rows = vars(pb)) +
  scale_color_ob + scale_linetype_nodesel_varsel +
  theme_publish() + xlab("cpu (seconds)") + ylab("\\%") + 
  coord_cartesian(expand = FALSE, ylim = c(0, NA), xlim = c(-10, 1797)) 
p
fName <- "fig_pref_oss.tex"
if (isFALSE(getOption('knitr.in.progress'))) {
  tikz(file = fName, standAlone=F)
  p
  dev.off()
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}
```










# Table 1

```{r}
options(knitr.table.format = "latex")

tabInput %>% 
  select(-range, -ratio) %>% 
  group_by(pb) %>% 
  kable(digits = c(0,0,1), 
        align = c("l", "l", "c"),
        escape = F,
        col.names = c("", str_c("$n$", footnote_marker_alphabet(1)), str_c("\\#", footnote_marker_alphabet(2))),
        caption = "Instances used.",
        booktabs = T,
        label = "input") %>% 
  add_footnote(label = c("Number of variables.", "Number of instances for each variable size")) 
```



# Table 2

```{r}
dat <- datAll %>% 
  group_by(instance) %>%
  filter(n() == algConfigsN, min(solved) == 1) %>%
  ungroup() 
winSeq <- unique(dat$algConfig)
getResGroup <- function(dat, ...) {
  # winSeq <- dat %>% 
  #   group_by(algConfig) %>% 
  #   summarize(cpu = mean(tpstotal)) %>% 
  #   mutate(pct = cpu/min(cpu), strV = str_c(algConfig, " (", round((pct-1) * 100), "%)")) %>% 
  #   arrange(cpu) %>% pull(algConfig)
  cols = c("cpu", "cpuLB", "nodes", "prune")  # columns for each group
  colN <- purrr::flatten_chr(map(cols, function(x) str_c(x, winSeq, sep = "_")))
  idx <- {
    lgd <- length(winSeq)
    idx <- NULL
    for (i in 1:length(winSeq))
      for (j in 1:length(cols))
        idx <- c(idx, i + (j-1)*lgd)
    idx
  }
  colN <- colN[idx]
  
  datYN <- dat %>% 
    group_by(instance, ...) %>% 
    summarise(YN = max(YN), YNse = max(YNse), YNs = max(YNs)) %>% 
    group_by(...) %>% 
    summarise(YN = mean(YN), YNse = mean(YNse), YNs = mean(YNs)) 

  datResults <- dat %>% 
    group_by(..., algConfig) %>% 
    summarise(ct = n(), cpu = mean(tpstotal), cpuMax = max(tpstotal), cpuMin = min(tpstotal), 
              nodes = mean(nbnodes), nInf = mean(pctinfeas), nOpt = mean(pctopt), nDom = mean(pctdomi),
              dptLeaf = mean(avgdepthT), dptMinLeaf = mean(mindepthT), dptMaxLeaf = mean(maxdepthT),
              solved = min(solved), cpuLB = 1000*mean(tpsLB/nbLB)) %>% 
    full_join(datYN) %>% 
    mutate(cpu = if_else(cpu == min(cpu), str_c(round(cpu, 1), "!"), str_c(round(cpu, 1))),
           cpuLB = if_else(cpuLB == min(cpuLB), str_c(round(cpuLB, 1), "!"), str_c(round(cpuLB, 1))),
           nodes = if_else(nodes == min(nodes), str_c(round(nodes, 0), "!"), str_c(round(nodes, 0)))) %>% 
    ungroup() %>% 
    mutate(cpu = if_else(solved == 1, 
                         str_c(cpu, " [", round(cpuMin,1), ",", round(cpuMax,1), "]"), 
                         str_c(cpu, "*", " [", round(cpuMin,1), ",", round(cpuMax,1), "]")),
           YN = str_c(round(YN), " (", round(100*YNse/YN), "/", round(100*(YNs-YNse)/YN), "/", round(100*(YN-YNs)/YN), ")"),
           nodes = str_c(nodes, " [", round(dptMinLeaf), ",", round(dptLeaf), ",", round(dptMaxLeaf), "]"),
           prune = str_c("[", round(nInf), ",", round(nOpt), ",", round(nDom), "]")
           ) %>%
    select(-solved, -cpuMin, -cpuMax, -dptMinLeaf, -dptMaxLeaf, -dptLeaf, -nInf, -nOpt, -nDom) %>%
    pivot_wider(names_from = c(algConfig), values_from = c(cpu, cpuLB, nodes, prune)) %>%
    select(..., ct, YN, !!colN)
  return(datResults)
}
datResRows <- getResGroup(dat, pb, n)
tabResults <- NULL
for (p in unique(datResRows$pb)) {
  dat1 <- datResRows %>% filter(pb == p)
  dat2 <- getResGroup(dat, pb) %>% filter(pb == p)
  tabResults  <- bind_rows(tabResults, dat1, dat2)
}

colsN = c("cpu", "cpuLB", "nodes", "prune")
tabResults <- tabResults %>% 
  mutate_at(vars(contains(c("cpu", "cpuLB", "nodes"))), ~cell_spec(., format = "latex", bold = if_else(str_detect(., fixed("!")), T, F))) %>% 
  mutate_if(is.character, str_replace_all, pattern = "!", replacement = "")
# digits <- c(0,0,0,rep(c(1,0,0),algConfigsN))

tab1 <- tabResults[,1:16] %>% 
  select(-pb) %>% 
  kable(format = "latex",
    # digits = digits, 
    align = rep("c", 16),
    escape = F,
    label = "results1",
    # table.envir = NULL,
    booktabs = T,
    col.names = c(str_c("$n$", footnote_marker_alphabet(1)), 
                  str_c("\\#", footnote_marker_alphabet(2)), 
                  str_c("$|\\YN|$", footnote_marker_alphabet(3)),  
                  str_c(rep(colsN, 3),  
                        c(footnote_marker_alphabet(4),
                          footnote_marker_alphabet(5),
                          footnote_marker_alphabet(6),
                          footnote_marker_alphabet(7)))),
    caption = "Detailed results for all instances which have been solved to optimality for breath configurations. The winner among the configurations for a column has been highlighted in bold. Summary statistics for each problem class is given."
    ) %>% 
  
  add_footnote(label = c("Number of variables.", 
                         "Number of instances.", 
                         "Avg. number of non-dominated points (supported extreme, supported non-extreme and unsupported in percent).",
                         "Avg. cpu time (seconds). Square brackets contains the range.",
                         "Avg. cpu time (miliseconds) used to find the LB set per node where LB set found.",
                         "Avg. number of nodes in the branching tree. Square brackets contains the min, avg. and max depth of leaf nodes.",
                         "Percentages of leaf nodes pruned by infisibility, optimality and dominance."
                         )
               ) %>% 
  kable_styling(latex_options = "scale_down") %>% 
  add_header_above(c(" " = 3, "\\\\texttt{B|C}" = 4, "\\\\texttt{B|F}" = 4, "\\\\texttt{B|N}" = 4), escape = F) %>% 
  pack_rows("AP", min(which(tabResults$pb == "AP")), max(which(tabResults$pb == "AP"))) %>% 
  pack_rows("KP", min(which(tabResults$pb == "KP")), max(which(tabResults$pb == "KP"))) %>% 
  pack_rows("UFLP", min(which(tabResults$pb == "UFLP")), max(which(tabResults$pb == "UFLP"))) %>% 
  row_spec(c(max(which(tabResults$pb == "AP")), 
             max(which(tabResults$pb == "KP")), 
             max(which(tabResults$pb == "UFLP"))), bold = T) %>% 
  row_spec(c(max(which(tabResults$pb == "AP")),
             max(which(tabResults$pb == "AP"))-1,
             max(which(tabResults$pb == "KP")),
             max(which(tabResults$pb == "UFLP"))-1, 
             max(which(tabResults$pb == "KP"))-1),  hline_after = T) 


tab2 <- tabResults[,c(1:4, 17:ncol(tabResults))] %>% 
  select(-pb) %>% 
  kable(format = "latex",
    # digits = digits, 
    align = rep("c", 16),
    escape = F,
    label = "results2",
    # table.envir = NULL,
    booktabs = T,
    col.names = c(str_c("$n$", footnote_marker_alphabet(1)), 
                  str_c("\\#", footnote_marker_alphabet(2)), 
                  str_c("$|\\YN|$", footnote_marker_alphabet(3)),  
                  str_c(rep(colsN, 3),  
                        c(footnote_marker_alphabet(4),
                          footnote_marker_alphabet(5),
                          footnote_marker_alphabet(6),
                          footnote_marker_alphabet(7)))),
    caption = "Detailed results for all instances which have been solved to optimality for depth configurations. The winner among the configurations for a column has been highlighted in bold. Summary statistics for each problem class is given."
    ) %>% 
  add_footnote(label = c("Number of variables.", 
                         "Number of instances.", 
                         "Avg. number of non-dominated points (supported extreme, supported non-extreme and unsupported in percent).",
                         "Avg. cpu time (seconds). Square brackets contains the range.",
                         "Avg. cpu time (miliseconds) used to find the LB set per node where LB set found.",
                         "Avg. number of nodes in the branching tree. Square brackets contains the min, avg. and max depth of leaf nodes.",
                         "Percentages of leaf nodes pruned by infisibility, optimality and dominance."
                         )
               ) %>% 
  kable_styling(latex_options = "scale_down") %>% 
  add_header_above(c(" " = 3, "\\\\texttt{D|C}" = 4, "\\\\texttt{D|F}" = 4, "\\\\texttt{D|N}" = 4), escape = F) %>% 
  pack_rows("AP", min(which(tabResults$pb == "AP")), max(which(tabResults$pb == "AP"))) %>% 
  pack_rows("KP", min(which(tabResults$pb == "KP")), max(which(tabResults$pb == "KP"))) %>% 
  pack_rows("UFLP", min(which(tabResults$pb == "UFLP")), max(which(tabResults$pb == "UFLP"))) %>% 
  row_spec(c(max(which(tabResults$pb == "AP")), 
             max(which(tabResults$pb == "KP")), 
             max(which(tabResults$pb == "UFLP"))), bold = T) %>% 
  row_spec(c(max(which(tabResults$pb == "AP")),
             max(which(tabResults$pb == "AP"))-1,
             max(which(tabResults$pb == "KP")),
             max(which(tabResults$pb == "UFLP"))-1, 
             max(which(tabResults$pb == "KP"))-1),  hline_after = T) 

if (isFALSE(getOption('knitr.in.progress'))) {
  fName <- "tab_results1.tex"
  tab1 %>% save_kable(file = fName, )
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
  fName <- "tab_results2.tex"
  tab2 %>% save_kable(file = fName, )
  file.copy(fName, str_c(pathOverLeaf, "/", fName), overwrite = T)
}


  
```





