name: R script generating report files

on:
  push:
    paths:
      - .github/workflows/main_report.yaml
      - results/convert/*.R
      - results/*.json
      - results/report/*.Rmd
      - results/report/*.R
  schedule:
    - cron: '0 */6 * * *'

jobs:
  render:
    name: Generate report files
    runs-on: macOS-latest
    env:
      RGL_USE_NULL: TRUE
      DISPLAY: ":99"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew cask install xquartz
      - name: Install packages
        run: Rscript -e "install.packages('rmarkdown')"
      - name: Run R script main_report.R
        run: Rscript results/report/main_report.R
      - name: Commit results
        run: |
          git add .
          git commit --allow-empty -am 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git pull --rebase
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

